# Generated by Django 4.2.13 on 2025-08-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studentprofile_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='last_quiz_topic',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
